### ISSUE TITLE
False positive when local method references `this` but not in the analyzed lambda 

### ISSUE THREAD

**Issue by HellBrick** [HellBrick/NoCapture#1]
```csharp
		[Fact]
		public void NoFalsePositiveForNonCapturingLambdaInsideLocalMethod()
			=> _verifier
			.Source
			(
@"
using System;
using System.Collections.Generic;
using System.Linq;

[AttributeUsage( AttributeTargets.Parameter | AttributeTargets.Method )]
class NoCaptureAttribute : Attribute
{
}

class C
{
	private readonly int[] _numbers = { 42, 64, 128 };

	public IEnumerable<int> EnumerateNumbers()
	{
		return
			_numbers == null
			? Enumerable.Empty<int>()
			: EnumerateWithoutValidation();

		IEnumerable<int> EnumerateWithoutValidation()
			=> _numbers
			.WhereNoCapture( x => x == 42 );
	}
}

static class X
{
		public static IEnumerable<T> WhereNoCapture<T>( this IEnumerable<T> sequence, [NoCapture] Func<T, bool> predicate )
			=> sequence.Where( predicate );
}
"
			)
			.ShouldHaveNoDiagnostics();
```

Assert.Empty() Failure
Collection: [Test0.cs(24,21): error HBNoCapture: WhereNoCapture( predicate ) doesn't allow capturing lambdas. Captured variables: this.]
   at HellBrick.Diagnostics.Assertions.AnalyzerVerifier`3.ShouldHaveNoDiagnostics() in F:\Software\NoCapture\HellBrick.Diagnostics.Assertions\AnalyzerVerifier.cs:line 44
   at HellBrick.NoCapture.Analyzer.Test.NoCaptureTest.NoFalsePositiveForNonCapturingLambdaInsideLocalMethod() in F:\Software\NoCapture\HellBrick.NoCapture.Test\NoCaptureTest.cs:line 171

**Comment by HellBrick** [comment]
At first glance, it looks like a Roslyn bug: when `SemanticModel.AnalyzeDataFlow()` analyzes the lambda declared in a local method, it considers lambda to capture everything that the local method captures.
